import "dotenv/config";

import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient, type Prisma } from "@prisma/client";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL is required to seed destinations.");
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString }),
});

type DestinationSeed = Omit<
  Prisma.DestinationCreateInput,
  "attributes" | "destinationScores" | "recommendations"
> & {
  attributes: Omit<
    Prisma.DestinationAttributeCreateWithoutDestinationInput,
    "id" | "createdAt" | "updatedAt"
  >;
};

const approximateDataNote =
  "Seed data is approximate planning guidance for the MVP and is not real-time pricing, availability, visa, safety, or flight data.";

const destinations: DestinationSeed[] = [
  {
    slug: "mexico-city",
    country: "Mexico",
    city: "Mexico City",
    region: "Central Mexico",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 5,
    climate: "MILD",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Architecture", "Art", "Food", "History", "Museums"],
    preferredSeasons: ["spring", "fall", "winter"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Mexico City travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 10,
      foodScore: 10,
      nightlifeScore: 8,
      natureScore: 4,
      romanceScore: 7,
      adventureScore: 5,
      relaxationScore: 5,
      logisticsScore: 10,
    },
  },
  {
    slug: "oaxaca-city",
    country: "Mexico",
    city: "Oaxaca City",
    region: "Oaxaca",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 5,
    climate: "MILD",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Food", "Markets", "Art", "History", "Local festivals"],
    preferredSeasons: ["fall", "winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Oaxaca City travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 10,
      foodScore: 10,
      nightlifeScore: 6,
      natureScore: 6,
      romanceScore: 8,
      adventureScore: 5,
      relaxationScore: 7,
      logisticsScore: 8,
    },
  },
  {
    slug: "puerto-escondido",
    country: "Mexico",
    city: "Puerto Escondido",
    region: "Oaxaca Coast",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 6,
    climate: "WARM",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 8,
    interests: ["Beach time", "Nature", "Photography", "Wellness", "Food"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Puerto Escondido travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 10,
      cultureScore: 5,
      foodScore: 7,
      nightlifeScore: 6,
      natureScore: 8,
      romanceScore: 8,
      adventureScore: 8,
      relaxationScore: 9,
      logisticsScore: 6,
    },
  },
  {
    slug: "merida",
    country: "Mexico",
    city: "Merida",
    region: "Yucatan",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 5,
    climate: "WARM",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 7,
    interests: ["History", "Architecture", "Food", "Museums", "Local festivals"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Merida travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 4,
      cultureScore: 9,
      foodScore: 9,
      nightlifeScore: 5,
      natureScore: 7,
      romanceScore: 8,
      adventureScore: 6,
      relaxationScore: 8,
      logisticsScore: 8,
    },
  },
  {
    slug: "valladolid-yucatan",
    country: "Mexico",
    city: "Valladolid",
    region: "Yucatan",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "LOW",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 6,
    climate: "WARM",
    idealDurationMinDays: 2,
    idealDurationMaxDays: 5,
    interests: ["History", "Nature", "Photography", "Food"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: ["limited_accessibility"],
    externalBookingSearchLabel: "Valladolid Yucatan travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 2,
      cultureScore: 8,
      foodScore: 7,
      nightlifeScore: 3,
      natureScore: 8,
      romanceScore: 7,
      adventureScore: 7,
      relaxationScore: 7,
      logisticsScore: 6,
    },
  },
  {
    slug: "san-cristobal-de-las-casas",
    country: "Mexico",
    city: "San Cristobal de las Casas",
    region: "Chiapas Highlands",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "LOW",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 7,
    climate: "COOL",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 7,
    interests: ["History", "Nature", "Markets", "Photography", "Coffee"],
    preferredSeasons: ["winter", "spring", "fall"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: ["limited_accessibility"],
    externalBookingSearchLabel: "San Cristobal de las Casas travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 9,
      foodScore: 7,
      nightlifeScore: 4,
      natureScore: 9,
      romanceScore: 7,
      adventureScore: 8,
      relaxationScore: 6,
      logisticsScore: 5,
    },
  },
  {
    slug: "tulum",
    country: "Mexico",
    city: "Tulum",
    region: "Riviera Maya",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "HIGH",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 6,
    climate: "WARM",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 8,
    interests: ["Beach time", "Wellness", "Design hotels", "Food", "Nature"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Tulum travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 10,
      cultureScore: 6,
      foodScore: 8,
      nightlifeScore: 7,
      natureScore: 8,
      romanceScore: 9,
      adventureScore: 7,
      relaxationScore: 9,
      logisticsScore: 7,
    },
  },
  {
    slug: "isla-holbox",
    country: "Mexico",
    city: "Isla Holbox",
    region: "Quintana Roo",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 7,
    climate: "WARM",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Beach time", "Nature", "Photography", "Wellness"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: ["limited_accessibility"],
    externalBookingSearchLabel: "Isla Holbox travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 10,
      cultureScore: 4,
      foodScore: 7,
      nightlifeScore: 3,
      natureScore: 9,
      romanceScore: 9,
      adventureScore: 6,
      relaxationScore: 10,
      logisticsScore: 5,
    },
  },
  {
    slug: "bacalar",
    country: "Mexico",
    city: "Bacalar",
    region: "Quintana Roo",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 7,
    climate: "WARM",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Nature", "Wellness", "Photography", "Beach time"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Bacalar travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 8,
      cultureScore: 5,
      foodScore: 6,
      nightlifeScore: 3,
      natureScore: 10,
      romanceScore: 9,
      adventureScore: 6,
      relaxationScore: 10,
      logisticsScore: 6,
    },
  },
  {
    slug: "guadalajara",
    country: "Mexico",
    city: "Guadalajara",
    region: "Jalisco",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 5,
    climate: "MILD",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Architecture", "Food", "Art", "History", "Shopping"],
    preferredSeasons: ["fall", "winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Guadalajara travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 8,
      foodScore: 9,
      nightlifeScore: 8,
      natureScore: 5,
      romanceScore: 7,
      adventureScore: 5,
      relaxationScore: 6,
      logisticsScore: 9,
    },
  },
  {
    slug: "guanajuato",
    country: "Mexico",
    city: "Guanajuato",
    region: "Bajio",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "LOW",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 6,
    climate: "MILD",
    idealDurationMinDays: 2,
    idealDurationMaxDays: 5,
    interests: ["Architecture", "History", "Museums", "Photography"],
    preferredSeasons: ["fall", "winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: ["limited_accessibility"],
    externalBookingSearchLabel: "Guanajuato travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 9,
      foodScore: 7,
      nightlifeScore: 6,
      natureScore: 5,
      romanceScore: 8,
      adventureScore: 5,
      relaxationScore: 6,
      logisticsScore: 7,
    },
  },
  {
    slug: "san-miguel-de-allende",
    country: "Mexico",
    city: "San Miguel de Allende",
    region: "Bajio",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "HIGH",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 6,
    climate: "MILD",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Architecture", "Art", "Design hotels", "Food", "Shopping"],
    preferredSeasons: ["fall", "winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: ["limited_accessibility"],
    externalBookingSearchLabel: "San Miguel de Allende travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 9,
      foodScore: 8,
      nightlifeScore: 5,
      natureScore: 5,
      romanceScore: 10,
      adventureScore: 4,
      relaxationScore: 8,
      logisticsScore: 7,
    },
  },
  {
    slug: "queretaro",
    country: "Mexico",
    city: "Queretaro",
    region: "Bajio",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 5,
    climate: "MILD",
    idealDurationMinDays: 2,
    idealDurationMaxDays: 5,
    interests: ["Architecture", "Food", "History", "Wine and spirits"],
    preferredSeasons: ["fall", "winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Queretaro travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 8,
      foodScore: 8,
      nightlifeScore: 5,
      natureScore: 6,
      romanceScore: 7,
      adventureScore: 5,
      relaxationScore: 7,
      logisticsScore: 8,
    },
  },
  {
    slug: "puebla",
    country: "Mexico",
    city: "Puebla",
    region: "Central Mexico",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "LOW",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 5,
    climate: "MILD",
    idealDurationMinDays: 2,
    idealDurationMaxDays: 5,
    interests: ["Architecture", "Food", "History", "Museums"],
    preferredSeasons: ["winter", "spring", "fall"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Puebla travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 9,
      foodScore: 9,
      nightlifeScore: 5,
      natureScore: 5,
      romanceScore: 7,
      adventureScore: 4,
      relaxationScore: 6,
      logisticsScore: 8,
    },
  },
  {
    slug: "valle-de-guadalupe",
    country: "Mexico",
    city: "Valle de Guadalupe",
    region: "Baja California",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "HIGH",
    minFlightDurationHours: 3,
    maxFlightDurationHours: 7,
    climate: "MILD",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 5,
    interests: ["Food", "Wine and spirits", "Design hotels", "Photography"],
    preferredSeasons: ["spring", "fall"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Valle de Guadalupe travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 4,
      cultureScore: 6,
      foodScore: 10,
      nightlifeScore: 4,
      natureScore: 7,
      romanceScore: 10,
      adventureScore: 4,
      relaxationScore: 9,
      logisticsScore: 6,
    },
  },
  {
    slug: "la-paz-baja-california-sur",
    country: "Mexico",
    city: "La Paz",
    region: "Baja California Sur",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 3,
    maxFlightDurationHours: 7,
    climate: "WARM",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 7,
    interests: ["Beach time", "Nature", "Adventure", "Photography"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "La Paz Baja California Sur travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 9,
      cultureScore: 5,
      foodScore: 7,
      nightlifeScore: 4,
      natureScore: 10,
      romanceScore: 8,
      adventureScore: 9,
      relaxationScore: 9,
      logisticsScore: 7,
    },
  },
  {
    slug: "los-cabos",
    country: "Mexico",
    city: "Los Cabos",
    region: "Baja California Sur",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "LUXURY",
    minFlightDurationHours: 3,
    maxFlightDurationHours: 7,
    climate: "WARM",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 7,
    interests: ["Beach time", "Design hotels", "Wellness", "Food", "Adventure"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Los Cabos travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 9,
      cultureScore: 4,
      foodScore: 8,
      nightlifeScore: 7,
      natureScore: 8,
      romanceScore: 10,
      adventureScore: 7,
      relaxationScore: 10,
      logisticsScore: 8,
    },
  },
  {
    slug: "mazatlan",
    country: "Mexico",
    city: "Mazatlan",
    region: "Sinaloa",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 6,
    climate: "WARM",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Beach time", "Food", "History", "Nightlife"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Mazatlan travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 8,
      cultureScore: 6,
      foodScore: 8,
      nightlifeScore: 7,
      natureScore: 6,
      romanceScore: 7,
      adventureScore: 5,
      relaxationScore: 8,
      logisticsScore: 8,
    },
  },
  {
    slug: "sayulita",
    country: "Mexico",
    city: "Sayulita",
    region: "Nayarit",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 6,
    climate: "WARM",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Beach time", "Adventure", "Wellness", "Photography"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Sayulita travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 9,
      cultureScore: 5,
      foodScore: 7,
      nightlifeScore: 6,
      natureScore: 8,
      romanceScore: 8,
      adventureScore: 8,
      relaxationScore: 8,
      logisticsScore: 7,
    },
  },
  {
    slug: "tequila-jalisco",
    country: "Mexico",
    city: "Tequila",
    region: "Jalisco",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "LOW",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 5,
    climate: "WARM",
    idealDurationMinDays: 2,
    idealDurationMaxDays: 4,
    interests: ["Food", "Wine and spirits", "History", "Photography"],
    preferredSeasons: ["winter", "spring", "fall"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Tequila Jalisco travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 7,
      foodScore: 8,
      nightlifeScore: 5,
      natureScore: 6,
      romanceScore: 7,
      adventureScore: 4,
      relaxationScore: 7,
      logisticsScore: 7,
    },
  },
  {
    slug: "cancun",
    country: "Mexico",
    city: "Cancun",
    region: "Quintana Roo",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "HIGH",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 6,
    climate: "WARM",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 7,
    interests: ["Beach time", "Nightlife", "Shopping", "Food"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Cancun travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 10,
      cultureScore: 4,
      foodScore: 7,
      nightlifeScore: 9,
      natureScore: 6,
      romanceScore: 8,
      adventureScore: 6,
      relaxationScore: 8,
      logisticsScore: 10,
    },
  },
  {
    slug: "monterrey",
    country: "Mexico",
    city: "Monterrey",
    region: "Nuevo Leon",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 5,
    climate: "WARM",
    idealDurationMinDays: 2,
    idealDurationMaxDays: 5,
    interests: ["Food", "Adventure", "Museums", "Shopping", "Nature"],
    preferredSeasons: ["winter", "spring", "fall"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Monterrey travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 6,
      foodScore: 8,
      nightlifeScore: 7,
      natureScore: 8,
      romanceScore: 5,
      adventureScore: 9,
      relaxationScore: 5,
      logisticsScore: 9,
    },
  },
  {
    slug: "zihuatanejo",
    country: "Mexico",
    city: "Zihuatanejo",
    region: "Guerrero",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 6,
    climate: "WARM",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 7,
    interests: ["Beach time", "Food", "Wellness", "Photography"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Zihuatanejo travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 9,
      cultureScore: 5,
      foodScore: 7,
      nightlifeScore: 4,
      natureScore: 7,
      romanceScore: 8,
      adventureScore: 5,
      relaxationScore: 9,
      logisticsScore: 6,
    },
  },
  {
    slug: "campeche",
    country: "Mexico",
    city: "Campeche",
    region: "Campeche",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "LOW",
    minFlightDurationHours: 2,
    maxFlightDurationHours: 6,
    climate: "WARM",
    idealDurationMinDays: 2,
    idealDurationMaxDays: 5,
    interests: ["History", "Architecture", "Food", "Photography"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Campeche travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 4,
      cultureScore: 8,
      foodScore: 7,
      nightlifeScore: 3,
      natureScore: 6,
      romanceScore: 7,
      adventureScore: 4,
      relaxationScore: 8,
      logisticsScore: 6,
    },
  },
  {
    slug: "morelia",
    country: "Mexico",
    city: "Morelia",
    region: "Michoacan",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "LOW",
    minFlightDurationHours: 1,
    maxFlightDurationHours: 6,
    climate: "MILD",
    idealDurationMinDays: 2,
    idealDurationMaxDays: 5,
    interests: ["Architecture", "History", "Food", "Museums"],
    preferredSeasons: ["fall", "winter", "spring"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Morelia travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 8,
      foodScore: 8,
      nightlifeScore: 4,
      natureScore: 5,
      romanceScore: 7,
      adventureScore: 4,
      relaxationScore: 6,
      logisticsScore: 7,
    },
  },
  {
    slug: "ensenada",
    country: "Mexico",
    city: "Ensenada",
    region: "Baja California",
    isDomestic: true,
    destinationScope: "MEXICO",
    budgetTier: "MID",
    minFlightDurationHours: 3,
    maxFlightDurationHours: 7,
    climate: "MILD",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 5,
    interests: ["Food", "Wine and spirits", "Beach time", "Nature"],
    preferredSeasons: ["spring", "fall"],
    visaConsiderations: "Domestic option for Mexico-based travelers.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Ensenada travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 6,
      cultureScore: 5,
      foodScore: 9,
      nightlifeScore: 5,
      natureScore: 7,
      romanceScore: 8,
      adventureScore: 5,
      relaxationScore: 8,
      logisticsScore: 6,
    },
  },
  {
    slug: "new-orleans",
    country: "United States",
    city: "New Orleans",
    region: "Louisiana",
    isDomestic: false,
    destinationScope: "NORTH_AMERICA",
    budgetTier: "HIGH",
    minFlightDurationHours: 3,
    maxFlightDurationHours: 8,
    climate: "WARM",
    idealDurationMinDays: 3,
    idealDurationMaxDays: 6,
    interests: ["Food", "History", "Nightlife", "Museums", "Local festivals"],
    preferredSeasons: ["winter", "spring", "fall"],
    visaConsiderations: "Passport and applicable US entry requirements may apply.",
    restrictedConditions: [],
    externalBookingSearchLabel: "New Orleans travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 9,
      foodScore: 10,
      nightlifeScore: 10,
      natureScore: 4,
      romanceScore: 7,
      adventureScore: 5,
      relaxationScore: 5,
      logisticsScore: 8,
    },
  },
  {
    slug: "vancouver",
    country: "Canada",
    city: "Vancouver",
    region: "British Columbia",
    isDomestic: false,
    destinationScope: "NORTH_AMERICA",
    budgetTier: "HIGH",
    minFlightDurationHours: 5,
    maxFlightDurationHours: 10,
    climate: "COOL",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 8,
    interests: ["Nature", "Food", "Photography", "Adventure", "Museums"],
    preferredSeasons: ["spring", "summer", "fall"],
    visaConsiderations: "Passport and applicable Canadian entry requirements may apply.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Vancouver travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 4,
      cultureScore: 7,
      foodScore: 9,
      nightlifeScore: 6,
      natureScore: 10,
      romanceScore: 8,
      adventureScore: 9,
      relaxationScore: 7,
      logisticsScore: 8,
    },
  },
  {
    slug: "antigua-guatemala",
    country: "Guatemala",
    city: "Antigua",
    region: "Central Highlands",
    isDomestic: false,
    destinationScope: "INTERNATIONAL",
    budgetTier: "MID",
    minFlightDurationHours: 3,
    maxFlightDurationHours: 8,
    climate: "MILD",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 8,
    interests: ["Architecture", "Food", "History", "Coffee", "Photography"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Passport and Guatemala entry requirements may apply.",
    restrictedConditions: ["limited_accessibility"],
    externalBookingSearchLabel: "Antigua Guatemala travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 1,
      cultureScore: 9,
      foodScore: 8,
      nightlifeScore: 5,
      natureScore: 8,
      romanceScore: 8,
      adventureScore: 7,
      relaxationScore: 7,
      logisticsScore: 6,
    },
  },
  {
    slug: "cartagena-colombia",
    country: "Colombia",
    city: "Cartagena",
    region: "Caribbean Coast",
    isDomestic: false,
    destinationScope: "INTERNATIONAL",
    budgetTier: "MID",
    minFlightDurationHours: 5,
    maxFlightDurationHours: 10,
    climate: "WARM",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 8,
    interests: ["Beach time", "Architecture", "Food", "Nightlife", "History"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Passport and Colombia entry requirements may apply.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Cartagena Colombia travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 8,
      cultureScore: 9,
      foodScore: 8,
      nightlifeScore: 8,
      natureScore: 6,
      romanceScore: 9,
      adventureScore: 5,
      relaxationScore: 8,
      logisticsScore: 7,
    },
  },
  {
    slug: "san-jose-costa-rica",
    country: "Costa Rica",
    city: "San Jose",
    region: "Central Valley",
    isDomestic: false,
    destinationScope: "INTERNATIONAL",
    budgetTier: "MID",
    minFlightDurationHours: 4,
    maxFlightDurationHours: 9,
    climate: "MILD",
    idealDurationMinDays: 5,
    idealDurationMaxDays: 9,
    interests: ["Nature", "Adventure", "Coffee", "Wellness", "Photography"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Passport and Costa Rica entry requirements may apply.",
    restrictedConditions: [],
    externalBookingSearchLabel: "Costa Rica travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 5,
      cultureScore: 6,
      foodScore: 7,
      nightlifeScore: 5,
      natureScore: 10,
      romanceScore: 8,
      adventureScore: 10,
      relaxationScore: 8,
      logisticsScore: 7,
    },
  },
  {
    slug: "san-juan-puerto-rico",
    country: "Puerto Rico",
    city: "San Juan",
    region: "Caribbean",
    isDomestic: false,
    destinationScope: "INTERNATIONAL",
    budgetTier: "HIGH",
    minFlightDurationHours: 5,
    maxFlightDurationHours: 10,
    climate: "WARM",
    idealDurationMinDays: 4,
    idealDurationMaxDays: 8,
    interests: ["Beach time", "History", "Food", "Nightlife", "Photography"],
    preferredSeasons: ["winter", "spring"],
    visaConsiderations: "Passport and applicable entry requirements may apply.",
    restrictedConditions: [],
    externalBookingSearchLabel: "San Juan Puerto Rico travel booking options",
    approximateDataNote,
    attributes: {
      beachScore: 9,
      cultureScore: 8,
      foodScore: 8,
      nightlifeScore: 8,
      natureScore: 7,
      romanceScore: 8,
      adventureScore: 6,
      relaxationScore: 8,
      logisticsScore: 7,
    },
  },
];

async function main() {
  for (const destination of destinations) {
    const { attributes, ...destinationData } = destination;

    await prisma.destination.upsert({
      where: { slug: destination.slug },
      update: {
        ...destinationData,
        attributes: {
          upsert: {
            create: attributes,
            update: attributes,
          },
        },
      },
      create: {
        ...destinationData,
        attributes: {
          create: attributes,
        },
      },
    });
  }

  console.log(`Seeded ${destinations.length} destinations.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
